- hosts: all
  remote_user: ubuntu
  tasks:
  -  name: delete old deployment
     ansible.builtin.command: kubectl delete -f /home/ubuntu/deployment.yml
  -  name: apply deployment
     ansible.builtin.command: kubectl apply -f /home/ubuntu/deployment.yml
  -  name: apply deployment
     ansible.builtin.command: kubectl apply -f /home/ubuntu/service.yml