apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devops-deploy
  name: devops-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30333
  selector:
    app: devops-deploy
  type: NodePort